[build.env]
passthrough = ["VERSION"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "sudo apt-get update",
    "sudo apt-get install -y libxcb1-dev libxkbcommon-x11-dev libxkbcommon-dev",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "sudo apt-get update",
    "sudo apt-get install -y libxcb1-dev libxkbcommon-x11-dev libxkbcommon-dev",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "sudo apt-get update",
    "sudo apt-get install -y libxcb1-dev libxkbcommon-x11-dev libxkbcommon-dev",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "sudo apt-get update",
    "sudo apt-get install -y libxcb1-dev libxkbcommon-x11-dev libxkbcommon-dev",
]
