name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $VERSION --draft --generate-notes --verify-tag --title $VERSION
    outputs:
      version: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ["create-release"]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            format: deb
            suffix: x64
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            format: deb
            suffix: x64
          - os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-musl
            format: deb
            suffix: aarch64
          - os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            format: deb
            suffix: aarch64

          - os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            format: dmg
            suffix: aarch64
          - os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            format: dmg
            suffix: x64

          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            format: nsis
            suffix: x64-setup
          - os: windows-latest
            rust: stable
            target: aarch64-pc-windows-msvc
            format: nsis
            suffix: arm64-setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Set target variables
        shell: bash
        run: |
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "FORMAT_FLAGS=--formats ${{ matrix.format }}" >> $GITHUB_ENV

      - name: Show command used for Cargo
        shell: bash
        run: |
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "format flag is: ${{ env.FORMAT_FLAGS }}"

      - name: Install dependencies
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb libxkbcommon-x11-dev libxkbcommon

      - name: Build release binary
        shell: bash
        run: |
          cargo install cross --locked
          cargo install cargo-packager --locked
          cross build --verbose --release ${{ env.TARGET_FLAGS }}
          cargo packager --verbose --release ${{ env.TARGET_FLAGS }} ${{ env.FORMAT_FLAGS }}
        env:
          VERSION: ${{ needs.create-release.outputs.version }}

      - name: Upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'windows-latest'
        run: |
          version="${{ needs.create-release.outputs.version }}"
          release_dir="target/${{ matrix.target }}/release"
          ori_name="Bustop_0.1.0_${{ matrix.suffix }}"
          to_name="bustop-$version-${{ matrix.target }}"
          mv ${release_dir}/${ori_name}.exe ${release_dir}/${to_name}.exe
          gh release upload "$version" ${release_dir}/${to_name}.exe

      - name: Upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          version="${{ needs.create-release.outputs.version }}"
          release_dir="target/${{ matrix.target }}/release"
          ori_name="Bustop_0.1.0_${{ matrix.suffix }}"
          to_name="bustop-$version-${{ matrix.target }}"
          mv ${release_dir}/${ori_name}.deb ${release_dir}/${to_name}.deb
          gh release upload "$version" ${release_dir}/${to_name}.deb

      - name: Upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'macos-latest'
        run: |
          version="${{ needs.create-release.outputs.version }}"
          release_dir="target/${{ matrix.target }}/release"
          ori_name="Bustop_0.1.0_${{ matrix.suffix }}"
          to_name="bustop-$version-${{ matrix.target }}"
          mv ${release_dir}/${ori_name}.dmg ${release_dir}/${to_name}.dmg
          gh release upload "$version" ${release_dir}/${to_name}.dmg
