name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
    outputs:
      version: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ["create-release"]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            format: deb
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            format: deb
          - os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-musl
            format: deb
          - os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            format: deb

          - os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            format: app
          - os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            format: app

          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            format: nsis
          - os: windows-latest
            rust: stable
            target: aarch64-pc-windows-msvc
            format: nsis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Set target variables
        shell: bash
        run: |
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "FORMAT_FLAGS=--formats ${{ matrix.format }}" >> $GITHUB_ENV

      - name: Show command used for Cargo
        shell: bash
        run: |
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "format flag is: ${{ env.FORMAT_FLAGS }}"

      - name: Build release binary
        shell: bash
        run: |
          cargo install cargo-packager --locked
          cross packager --verbose --release ${{ env.TARGET_FLAGS }} ${{ env.FORMAT_FLAGS }}
        env:
          VERSION: ${{ needs.create-release.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/*.app
            target/release/*.exe
            target/release/*.deb
